leaveprogram=0
while leaveprogram != "q":
    import random
    print("This is a dice rolling program")
    print("press enter to roll")
    input()
    number=random.randint(1, 6)
    if number==1:
        print("[------------]")
        print("[            ]")
        print("[     o      ]")
        print("[            ]")
        print("[------------]")
        print()
        print("Type 'q' to quit")
    if number==2:
        print("[------------]")
        print("[            ]")
        print("[  o     o   ]")
        print("[            ]")
        print("[------------]")
        print("Type 'q' to quit")
        leaveprogram=input()
    if number==3:
        print("[------------]")
        print("[   o   o    ]")
        print("[     o      ]")
        print("[            ]")
        print("[------------]")
        print("Type 'q' to quit")
        leaveprogram=input()
    if number==4:
        print("[------------]")
        print("[   o   o    ]")
        print("[   o   o    ]")
        print("[            ]")
        print("[------------]")
        print("Type 'q' to quit")
        leaveprogram=input()
    if number==5:
        print("[------------]")
        print("[   o   o    ]")
        print("[     o      ]")
        print("[   o   o    ]")
        print("[------------]")
        print("Type 'q' to quit")
        leaveprogram=input()
    if number==6:
        print("[------------]")
        print("[   o   o    ]")
        print("[   o   o    ]")
        print("[   o   o    ]")
        print("[------------]")
        print("Type 'q' to quit")
        leaveprogram=input()
